# This is a config for E2B sandbox template.
# You can use template ID (lerq7j337hk8pxxbny3k) or template name (vibe-nextjs15) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs15") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs15") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs15')

team_id = "c05805ad-f0e6-4244-b06f-090de7ce6b61"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs15"
template_id = "lerq7j337hk8pxxbny3k"
